

server:
  port: 8123
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vms?serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
        format_sql: true
    show-sql: true
    open-in-view: true


